name: Android Build with Debugging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify your Python version

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK and NDK
      run: |
        # sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        mkdir -p "$HOME/.buildozer/android/platform"
        curl -s "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -o android_tools.zip
        unzip android_tools.zip -d "$HOME/.buildozer/android/platform"
        yes | $HOME/.buildozer/android/platform/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform --licenses
        $HOME/.buildozer/android/platform/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3" "extras;android;m2repository"

    - name: Set Permissions for Android Directories
      run: |
        sudo chmod -R 777 "$HOME/.buildozer/android"

    - name: Run Buildozer Build
      env:
        ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform
        ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform
      run: |
        buildozer android debug 
       
         buildozer_version: stable

    - name: Upload Build Logs
      uses: actions/upload-artifact@v3
      with:
        name: build-log
        path: build.log
